# Generated by Django 4.1.6 on 2023-05-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_way', '0006_alter_services_contact_alter_services_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_for',
            field=models.TextField(default='vis'),
            preserve_default=False,
        ),
    ]
